// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/categories/api/datasource_implementation/categories_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/features/categories/api/client/categories_api_client.dart'
    as _i4;
import 'package:flower_app/features/categories/data/models/categories_response.dart'
    as _i2;
import 'package:flower_app/features/categories/data/models/categoryResponse_byId_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.CategoriesResponse {
  _FakeCategoriesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryDetailsResponse_1 extends _i1.SmartFake
    implements _i3.CategoryDetailsResponse {
  _FakeCategoryDetailsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryApiClient extends _i1.Mock implements _i4.CategoryApiClient {
  MockCategoryApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CategoriesResponse> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue:
            _i5.Future<_i2.CategoriesResponse>.value(_FakeCategoriesResponse_0(
          this,
          Invocation.method(
            #getAllCategories,
            [],
          ),
        )),
      ) as _i5.Future<_i2.CategoriesResponse>);

  @override
  _i5.Future<_i3.CategoryDetailsResponse> getCategoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i5.Future<_i3.CategoryDetailsResponse>.value(
            _FakeCategoryDetailsResponse_1(
          this,
          Invocation.method(
            #getCategoryById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.CategoryDetailsResponse>);
}
