// Mocks generated by Mockito 5.4.4 from annotations
// in flower_app/test/features/track_order/data/repositories_implementation/order_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/features/track_order/data/datasources/order_remote_data_source.dart'
    as _i3;
import 'package:flower_app/features/track_order/data/models/order_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePickupAddressModel_0 extends _i1.SmartFake
    implements _i2.PickupAddressModel {
  _FakePickupAddressModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserAddressModel_1 extends _i1.SmartFake
    implements _i2.UserAddressModel {
  _FakeUserAddressModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRemoteDataSource extends _i1.Mock
    implements _i3.OrderRemoteDataSource {
  MockOrderRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.OrderModel?> getOrderById({
    required String? userId,
    required String? orderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderById,
          [],
          {
            #userId: userId,
            #orderId: orderId,
          },
        ),
        returnValue: _i4.Future<_i2.OrderModel?>.value(),
      ) as _i4.Future<_i2.OrderModel?>);

  @override
  _i4.Stream<_i2.OrderModel?> watchOrderById({
    required String? userId,
    required String? orderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchOrderById,
          [],
          {
            #userId: userId,
            #orderId: orderId,
          },
        ),
        returnValue: _i4.Stream<_i2.OrderModel?>.empty(),
      ) as _i4.Stream<_i2.OrderModel?>);
}

/// A class which mocks [OrderModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderModel extends _i1.Mock implements _i2.OrderModel {
  MockOrderModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  bool get arrivedAtPickup => (super.noSuchMethod(
        Invocation.getter(#arrivedAtPickup),
        returnValue: false,
      ) as bool);

  @override
  int get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: 0,
      ) as int);

  @override
  String get driverId => (super.noSuchMethod(
        Invocation.getter(#driverId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#driverId),
        ),
      ) as String);

  @override
  List<_i2.OrderItemModel> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i2.OrderItemModel>[],
      ) as List<_i2.OrderItemModel>);

  @override
  int get lastUpdated => (super.noSuchMethod(
        Invocation.getter(#lastUpdated),
        returnValue: 0,
      ) as int);

  @override
  String get orderNumber => (super.noSuchMethod(
        Invocation.getter(#orderNumber),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#orderNumber),
        ),
      ) as String);

  @override
  String get paymentMethod => (super.noSuchMethod(
        Invocation.getter(#paymentMethod),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#paymentMethod),
        ),
      ) as String);

  @override
  _i2.PickupAddressModel get pickupAddress => (super.noSuchMethod(
        Invocation.getter(#pickupAddress),
        returnValue: _FakePickupAddressModel_0(
          this,
          Invocation.getter(#pickupAddress),
        ),
      ) as _i2.PickupAddressModel);

  @override
  String get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
      ) as String);

  @override
  int get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0,
      ) as int);

  @override
  String get updateOrderButton => (super.noSuchMethod(
        Invocation.getter(#updateOrderButton),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#updateOrderButton),
        ),
      ) as String);

  @override
  _i2.UserAddressModel get userAddress => (super.noSuchMethod(
        Invocation.getter(#userAddress),
        returnValue: _FakeUserAddressModel_1(
          this,
          Invocation.getter(#userAddress),
        ),
      ) as _i2.UserAddressModel);
}
