// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/most_selling_products/api/datasource_impl/product_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/features/most_selling_products/api/client/product_api_client.dart'
    as _i3;
import 'package:flower_app/features/most_selling_products/data/models/products_reponse_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductsResponseModel_0 extends _i1.SmartFake
    implements _i2.ProductsResponseModel {
  _FakeProductsResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductApiClient extends _i1.Mock implements _i3.ProductApiClient {
  MockProductApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProductsResponseModel> getAllProducts(
    String? sort,
    String? search,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [
            sort,
            search,
            category,
          ],
        ),
        returnValue: _i4.Future<_i2.ProductsResponseModel>.value(
            _FakeProductsResponseModel_0(
          this,
          Invocation.method(
            #getAllProducts,
            [
              sort,
              search,
              category,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ProductsResponseModel>);
}
