// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/api/datasource_impl/profile_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:flower_app/features/profile/api/client/profile_api_client.dart'
    as _i5;
import 'package:flower_app/features/profile/data/models/edit_profile_request_model.dart'
    as _i7;
import 'package:flower_app/features/profile/data/models/edit_profile_response_model.dart'
    as _i3;
import 'package:flower_app/features/profile/data/models/profile_response.dart'
    as _i2;
import 'package:flower_app/features/profile/data/models/upload_photo_response.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileResponse_0 extends _i1.SmartFake
    implements _i2.ProfileResponse {
  _FakeProfileResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseModel_1 extends _i1.SmartFake
    implements _i3.EditProfileResponseModel {
  _FakeEditProfileResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponse_2 extends _i1.SmartFake
    implements _i4.UploadPhotoResponse {
  _FakeUploadPhotoResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiClient extends _i1.Mock implements _i5.ProfileApiClient {
  MockProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ProfileResponse> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i6.Future<_i2.ProfileResponse>.value(_FakeProfileResponse_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ProfileResponse>);

  @override
  _i6.Future<_i3.EditProfileResponseModel> editProfile(
          _i7.EditProfileRequestModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [model],
        ),
        returnValue: _i6.Future<_i3.EditProfileResponseModel>.value(
            _FakeEditProfileResponseModel_1(
          this,
          Invocation.method(
            #editProfile,
            [model],
          ),
        )),
      ) as _i6.Future<_i3.EditProfileResponseModel>);

  @override
  _i6.Future<_i4.UploadPhotoResponse> uploadPhoto(_i8.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i6.Future<_i4.UploadPhotoResponse>.value(
            _FakeUploadPhotoResponse_2(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i6.Future<_i4.UploadPhotoResponse>);
}
